export const  dashboardTypes = {
    FETCH_DASHBOARD_DATA: "FETCH_DASHBOARD_DATA",
    FETCH_DASHBOARD_DATA_SUCCESS: "FETCH_DASHBOARD_DATA_SUCCESS",
    FETCH_DASHBOARD_DATA_FAILURE: "FETCH_DASHBOARD_DATA_FAILURE",
    UPDATE_DASHBOARD_FILTERS: "UPDATE_DASHBOARD_FILTERS",
    RESET_DASHBOARD_STATE: "RESET_DASHBOARD_STATE"
};