export const dashboardTypes = {
    API_RESPONSE_SUCCESS: "@@DASHBOARD/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@DASHBOARD/API_RESPONSE_ERROR",
    FETCH_DASHBOARD_DATA: "@@DASHBOARD/FETCH_DASHBOARD_DATA",
    FETCH_DASHBOARD_DATA_SUCCESS: "@@DASHBOARD/FETCH_DASHBOARD_DATA_SUCCESS",
    FETCH_DASHBOARD_DATA_FAILURE: "@@DASHBOARD/FETCH_DASHBOARD_DATA_FAILURE",
    UPDATE_DASHBOARD_FILTERS: "@@DASHBOARD/UPDATE_DASHBOARD_FILTERS",
    RESET_DASHBOARD_STATE: "@@DASHBOARD/RESET_DASHBOARD_STATE",
    SIGNIN: "@@DASHBOARD/SIGNIN",
    SUMMARY: "@@DASHBOARD/SUMMARY",
    MONTH_ACTIVITY: "@@DASHBOARD/MONTH_ACTIVITY",
    MONTH_TRANSACTIONS: "@@DASHBOARD/MONTH_TRANSACTIONS",
    BANKACCOUNT: "@@DASHBOARD/BANKACCOUNT",
    SUBSCRIPTION_TENANT_3: "@@DASHBOARD/SUBSCRIPTION_TENANT_3",
    SETTING_TYPES_LICENSE: "@@DASHBOARD/SETTING_TYPES_LICENSE",
    SETTING_TYPES_GENERAL: "@@DASHBOARD/SETTING_TYPES_GENERAL",
    CARDREPORTS: "@@DASHBOARD/CARDREPORTS",
    INNOVOICE_LAST: "@@DASHBOARD/INNOVOICE_LAST",
    ESTIMATES_LAST: "@@DASHBOARD/ESTIMATES_LAST",
    BILLS_LAST: "@@DASHBOARD/BILLS_LAST",
    TRANSACTIONS_LAST: "@@DASHBOARD/TRANSACTIONS_LAST",
    CURRENCY_DEFAULT: "@@DASHBOARD/CURRENCY_DEFAULT",
    REVENUE_TOTAL: "@@DASHBOARD/REVENUE_TOTAL",
    INVOICE_REPORT: "@@DASHBOARD/INVOICE_REPORT",
    GOALS_LAST: "@@DASHBOARD/GOALS_LAST",
};















