export const ChartAccountActionTypes = {
    API_RESPONSE_SUCCESS: "@@CHARTOFACCOUNT/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@CHARTOFACCOUNT/API_RESPONSE_ERROR",
    MANUALJOURNAL: "@@CHARTOFACCOUNT/MANUALJOURNAL",
    CURRENCY: "@@CHARTOFACCOUNT/CURRENCY",
    CHARTACCOUNTS: "@@CHARTOFACCOUNT/CHARTACCOUNTS",
    VENDOR: "@@CHARTOFACCOUNT/VENDOR",
    TAXE: "@@CHARTOFACCOUNT/TAXE",
    CUSTOMER: "@@CHARTOFACCOUNT/CUSTOMER",
    MANUALJOURNAL_3: "@@CHARTOFACCOUNT/MANUALJOURNAL_3",
    TRANSACTION: "@@CHARTOFACCOUNT/TRANSACTION",
};
