export const productAndServicesTypes = {
    API_RESPONSE_SUCCESS: "@@PRODUCT_AND_SERVICES/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@PRODUCT_AND_SERVICES/API_RESPONSE_ERROR",
    GET_PRODUCTS: "@@PRODUCT_AND_SERVICES/GET_PRODUCTS",
    GET_DEFAULT_CURRENCY: "@@PRODUCT_AND_SERVICES/GET_DEFAULT_CURRENCY",
    GET_SUBSCRIPTIONS_TENANTS_3: "@@PRODUCT_AND_SERVICES/GET_SUBSCRIPTIONS_TENANTS_3",
    GET_SERVICES: "@@PRODUCT_AND_SERVICES/GET_SERVICES",
}