// Redux/chats/types.js

export const ChatsActionTypes = {
  API_RESPONSE_SUCCESS: "@@chats/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR: "@@chats/API_RESPONSE_ERROR",

  GET_FAVOURITES: "@@chats/GET_FAVOURITES",
  GET_DIRECT_MESSAGES: "@@chats/GET_DIRECT_MESSAGES",
  GET_CHANNELS: "@@chats/GET_CHANNELS",

  ADD_CONTACTS: "@@chats/ADD_CONTACTS",
  CREATE_CHANNEL: "@@chats/CREATE_CHANNEL",
  CHANGE_SELECTED_CHAT: "@@chats/CHANGE_SELECTED_CHAT",
  GET_CHAT_USER_DETAILS: "@@chats/GET_CHAT_USER_DETAILS",
  GET_CHAT_USER_CONVERSATIONS: "@@chats/GET_CHAT_USER_CONVERSATIONS",
  TOGGLE_USER_DETAILS_TAB: "@@chats/TOGGLE_USER_DETAILS_TAB",

  // MESSAGE
  ON_SEND_MESSAGE: "@@chats/ON_SEND_MESSAGE",
  RECEIVE_MESSAGE: "@@chats/RECEIVE_MESSAGE",
  RECEIVE_MESSAGE_FROM_USER: "@@chats/RECEIVE_MESSAGE_FROM_USER",
  DELETE_MESSAGE: "@@chats/DELETE_MESSAGE",
  FORWARD_MESSAGE: "@@chats/FORWARD_MESSAGE",
  DELETE_USER_MESSAGES: "@@chats/DELETE_USER_MESSAGES",
  GET_CHANNEL_DETAILS: "@@chats/GET_CHANNEL_DETAILS",
  TOGGLE_FAVOURITE_CONTACT: "@@chats/TOGGLE_FAVOURITE_CONTACT",
  GET_ARCHIVE_CONTACT: "@@chats/GET_ARCHIVE_CONTACT",
  READ_CONVERSATION: "@@chats/READ_CONVERSATION",
  DELETE_IMAGE: "@@chats/DELETE_IMAGE",
  REPLY_IMAGE: "@@chats/REPLY_IMAGE",

  // Self-made
  ADD_MESSAGE_TO_CHAT_LIST: "@@chats/ADD_MESSAGE_TO_CHAT_LIST",
  ARCHIVE_CONTACT: "@@chats/ARCHIVE_CONTACT",
  UNARCHIVE_CONTACT: "@@chats/UNARCHIVE_CONTACT",
  RESET_USER_MESSAGE_DELETED: "@@chats/RESET_USER_MESSAGE_DELETED",
  ON_REPLY_MESSAGE: "@@chats/ON_REPLY_MESSAGE",
  READ_MESSAGE: "@@chats/READ_MESSAGE",
  READALL_MESSAGE: "@@chats/READALL_MESSAGE",
  UNREAD_MESSAGE: "@@chats/UNREAD_MESSAGE",
  GET_PINNED_CONTACT: "@@chats/GET_PINNED_CONTACT",
  PIN_CONTACT: "@@chats/PIN_CONTACT",
  UNPIN_CONTACT: "@@chats/UNPIN_CONTACT",
  STAR_CHAT: "@@chats/STAR_CHAT",
  UNSTAR_CHAT: "@@chats/UNSTAR_CHAT",
  GET_STARRED_CHATS: "@@chats/GET_STARRED_CHATS",
  NEW_MESSAGE_RECEIVED: "@@chats/NEW_MESSAGE_RECEIVED",
  INCREMENT_UNREAD: "@@chats/INCREMENT_UNREAD",
};
