export const expensesActionTypes = {
    FETCH_EXPENSES_REQUEST: "FETCH_EXPENSES_REQUEST",
    FETCH_EXPENSES_SUCCESS: "FETCH_EXPENSES_SUCCESS",
    FETCH_EXPENSES_FAILURE: "FETCH_EXPENSES_FAILURE",
    CREATE_EXPENSE_REQUEST: "CREATE_EXPENSE_REQUEST",
    CREATE_EXPENSE_SUCCESS: "CREATE_EXPENSE_SUCCESS",
    CREATE_EXPENSE_FAILURE: "CREATE_EXPENSE_FAILURE",
    UPDATE_EXPENSE_REQUEST: "UPDATE_EXPENSE_REQUEST",
    UPDATE_EXPENSE_SUCCESS: "UPDATE_EXPENSE_SUCCESS",
    UPDATE_EXPENSE_FAILURE: "UPDATE_EXPENSE_FAILURE",
    DELETE_EXPENSE_REQUEST: "DELETE_EXPENSE_REQUEST",
    DELETE_EXPENSE_SUCCESS: "DELETE_EXPENSE_SUCCESS",
    DELETE_EXPENSE_FAILURE: "DELETE_EXPENSE_FAILURE"
};