export const expensesActionTypes = {
    API_RESPONSE_SUCCESS: "@@EXPENSES/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@EXPENSES/API_RESPONSE_ERROR",
    BILL: "@@EXPENSES/BILL",
    PAYMENT: "@@EXPENSES/PAYMENT",
    DEFAULT_CURRENCY: "@@EXPENSES/DEFAULT_CURRENCY",
    DEBITNOTES: "@@EXPENSES/DEBITNOTES",
    VENDOR: "@@EXPENSES/VENDOR",
};