export const SettingsActionTypes = {
    API_RESPONSE_SUCCESS: "@@settings/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@settings/API_RESPONSE_ERROR",

    GET_SETTINGS_DATA: "@@settings/GET_SETTINGS_DATA",
    GET_SETTINGS_DATA_SUCCESS: "@@settings/GET_SETTINGS_DATA_SUCCESS",
    UPDATE_SETTINGS: "@@settings/UPDATE_SETTINGS",
    UPDATE_SETTINGS_SUCCESS: "@@settings/UPDATE_SETTINGS_SUCCESS",
    RESET_SETTINGS: "@@settings/RESET_SETTINGS",
};