export const bankAccountActionTypes = {
    API_RESPONSE_SUCCESS: "@@BANCKACCOUNT/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@BANCKACCOUNT/API_RESPONSE_ERROR",
    CURRENCY_DEFAULT: "@@BANCKACCOUNT/CURRENCY_DEFAULT",
    BANK_ACCOUNT: "@@BANCKACCOUNT/BANK_ACCOUNT",
};