export const bankAccountActionTypes = {
    API_RESPONSE_SUCCESS: "@@BANCKACCOUNT/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@BANCKACCOUNT/API_RESPONSE_ERROR",
    FETCH_BANK_ACCOUNTS: "@@BANCKACCOUNT/FETCH_BANK_ACCOUNTS",
    ADD_BANK_ACCOUNT: "@@BANCKACCOUNT/ADD_BANK_ACCOUNT",
    UPDATE_BANK_ACCOUNT: "@@BANCKACCOUNT/UPDATE_BANK_ACCOUNT",
    DELETE_BANK_ACCOUNT: "@@BANCKACCOUNT/DELETE_BANK_ACCOUNT",
    GET_BANK_ACCOUNT_DETAILS: "@@BANCKACCOUNT/GET_BANK_ACCOUNT_DETAILS",
    SET_SELECTED_BANK_ACCOUNT: "@@BANCKACCOUNT/SET_SELECTED_BANK_ACCOUNT",
    CLEAR_SELECTED_BANK_ACCOUNT: "@@BANCKACCOUNT/CLEAR_SELECTED_BANK_ACCOUNT",
};