export const bankAccountActionTypes = {
    FETCH_BANK_ACCOUNTS: "FETCH_BANK_ACCOUNTS",
    ADD_BANK_ACCOUNT: "ADD_BANK_ACCOUNT",
    UPDATE_BANK_ACCOUNT: "UPDATE_BANK_ACCOUNT",
    DELETE_BANK_ACCOUNT: "DELETE_BANK_ACCOUNT",
    GET_BANK_ACCOUNT_DETAILS: "GET_BANK_ACCOUNT_DETAILS",
    SET_SELECTED_BANK_ACCOUNT: "SET_SELECTED_BANK_ACCOUNT",
    CLEAR_SELECTED_BANK_ACCOUNT: "CLEAR_SELECTED_BANK_ACCOUNT",
};