export const salesActionTypes = {
    FETCH_SALES_REQUEST: "FETCH_SALES_REQUEST",
    FETCH_SALES_SUCCESS: "FETCH_SALES_SUCCESS",
    FETCH_SALES_FAILURE: "FETCH_SALES_FAILURE",
    CREATE_SALE_REQUEST: "CREATE_SALE_REQUEST",
    CREATE_SALE_SUCCESS: "CREATE_SALE_SUCCESS",
    CREATE_SALE_FAILURE: "CREATE_SALE_FAILURE",
    UPDATE_SALE_REQUEST: "UPDATE_SALE_REQUEST",
    UPDATE_SALE_SUCCESS: "UPDATE_SALE_SUCCESS",
    UPDATE_SALE_FAILURE: "UPDATE_SALE_FAILURE",
    DELETE_SALE_REQUEST: "DELETE_SALE_REQUEST",
    DELETE_SALE_SUCCESS: "DELETE_SALE_SUCCESS",
    DELETE_SALE_FAILURE: "DELETE_SALE_FAILURE"
}