export const salesActionTypes = {
    API_RESPONSE_SUCCESS: "@@SALES/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@SALES/API_RESPONSE_ERROR",
    PROPOSALS: "@@SALES/PROPOSALS",
    TENANTS_SUBSCRIPTION_3: "@@SALES/TENANTS_SUBSCRIPTION_3",
    INVOICE: "@@SALES/INVOICE",
    CUSTOMER: "@@SALES/CUSTOMER",
    CURRENCY: "@@SALES/CURRENCY",
    REVENUE: "@@SALES/REVENUE",
    DEFAULT_CURRENCY: "@@SALES/DEFAULT_CURRENCY",
    TOTAL_REVENUE: "@@SALES/TOTAL_REVENUE",
    GOAL: "@@SALES/GOAL",
    CREDITNOTES: "@@SALES/CREDITNOTES",
    EDIT_PROPOSAL_DATA: "@@SALES/EDIT_PROPOSAL_DATA",
    DELETE_PROPOSAL_DATA: "@@SALES/DELETE_PROPOSAL_DATA",
    EDIT_PROPOSAL_DATA_DETAILS: "@@SALES/EDIT_PROPOSAL_DATA_DETAILS",
    CREATE_PROPOSAL_DATA: "@@SALES/CREATE_PROPOSAL_DATA"
}