export const reportsActionTypes = {
    API_RESPONSE_SUCCESS: "@@REPORTS/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@REPORTS/API_RESPONSE_ERROR",
   CURRENCY_DEFAULT: "@@REPORTS/CURRENCY_DEFAULT",
    REPORT_PROFIT_AND_LOSS: "@@REPORTS/REPORT_PROFIT_AND_LOSS",
    REPORT_BALANCE_SHEET: "@@REPORTS/REPORT_BALANCE_SHEET",
    REPORT_TAX: "@@REPORTS/REPORT_TAX",
    REPORT_CUSTOMER: "@@REPORTS/REPORT_CUSTOMER",
    REPORT_VENDOR: "@@REPORTS/REPORT_VENDOR",
    REPORT_ACCOUNT_BALANCE: "@@REPORTS/REPORT_ACCOUNT_BALANCE",
    REPORT_TRIAL_BALANCE: "@@REPORTS/REPORT_TRIAL_BALANCE",
    REPORT_ACCOUNT_TRANSACTION: "@@REPORTS/REPORT_ACCOUNT_TRANSACTION",
  };
  