export const reportsActionTypes = {
    FETCH_REPORTS_REQUEST: "FETCH_REPORTS_REQUEST",
    FETCH_REPORTS_SUCCESS: "FETCH_REPORTS_SUCCESS",
    FETCH_REPORTS_FAILURE: "FETCH_REPORTS_FAILURE",
    CREATE_REPORT_REQUEST: "CREATE_REPORT_REQUEST",
    CREATE_REPORT_SUCCESS: "CREATE_REPORT_SUCCESS",
    CREATE_REPORT_FAILURE: "CREATE_REPORT_FAILURE",
    UPDATE_REPORT_REQUEST: "UPDATE_REPORT_REQUEST",
    UPDATE_REPORT_SUCCESS: "UPDATE_REPORT_SUCCESS",
    UPDATE_REPORT_FAILURE: "UPDATE_REPORT_FAILURE",
    DELETE_REPORT_REQUEST: "DELETE_REPORT_REQUEST",
    DELETE_REPORT_SUCCESS: "DELETE_REPORT_SUCCESS",
    DELETE_REPORT_FAILURE: "DELETE_REPORT_FAILURE"
}