export const ConsoleActionTypes = {
    API_RESPONSE_SUCCESS: "@@console/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@console/API_RESPONSE_ERROR",

    GET_CONSOLE_DATA: "@@console/GET_CONSOLE_DATA",
    GET_CONSOLE_DATA_SUCCESS: "@@console/GET_CONSOLE_DATA_SUCCESS",
    DELETE_CONSOLE_ENTRY: "@@console/DELETE_CONSOLE_ENTRY",
    DELETE_CONSOLE_ENTRY_SUCCESS: "@@console/DELETE_CONSOLE_ENTRY_SUCCESS",
    UPDATE_CONSOLE_ENTRY: "@@console/UPDATE_CONSOLE_ENTRY",
    UPDATE_CONSOLE_ENTRY_SUCCESS: "@@console/UPDATE_CONSOLE_ENTRY_SUCCESS",
}