export const ConsoleActionTypes = {
    API_RESPONSE_SUCCESS: "@@CONSOLE/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@CONSOLE/API_RESPONSE_ERROR",

    SUBSCRIPTIONS_TENANT_3: "@@CONSOLE/SUBSCRIPTIONS_TENANT_3",
    USERS_ALL: "@@CONSOLE/USERS_ALL",
    STRIPE_ACCOUNT_ALL: "@@CONSOLE/STRIPE_ACCOUNT_ALL",
    ROLES: "@@CONSOLE/ROLES",
    USERS: "@@CONSOLE/USERS",
    USERS_6_id: "@@CONSOLE/USERS_6_id",
    PLAN: "@@CONSOLE/PLAN",
    PLAN_ID: "@@CONSOLE/PLAN_ID",
    SUBSCRIPTIONS_ALL: "@@CONSOLE/SUBSCRIPTIONS_ALL",
    CURRENCY: "@@CONSOLE/CURRENCY",
    SETTING_TYPE_GENERAL: "@@CONSOLE/GENERAL",
    SETTING_TYPE_PAYMENT: "@@CONSOLE/SETTING_TYPE_PAYMENT",
    SETTING_TYPE_LICENSE: "@@CONSOLE/SETTING_TYPE_LICENSE",
    SETTING_TYPE_SOCIAL_LOGIN: "@@CONSOLE/SETTING_TYPE_SOCIAL_LOGIN",
    BANKACCOUNT: "@@CONSOLE/BANKACCOUNT",
    EN_JSON: "@@CONSOLE/EN_JSON",
    SETTING_TYPE_EMAIL: "@@CONSOLE/SETTING_TYPE_EMAIL",
    CREATEBANKACCOUNT: "@@CONSOLE/CREATEBANKACCOUNT"
}